version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventhub
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro 
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/eventhub?sslmode=disable
      JWT_SECRET: supersecretkey
    ports:
      - "8080:8080"

  

volumes:
  db_data:

